### PR TITLE
[bsmrk-gen01] - Create Base Project

### PR DESCRIPTION
**Pull request by Oscarz90**
resolves: #1 

### What does this PR do?

Implements the base of the project, using a lot of libraries for that purpose, includes a variety of them.

### How Has This Been Tested?

Executing every npm script available within the package.json file

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by acampos9 — APPROVED** [review]

**Review by acampos9 — COMMENTED** [review]
Error code monitor 
image

**Comment by Oscarz90** [comment]
> Error code monitor
> image

I made a test, here I left the evidence, it worked well:

[asciicast](https://asciinema.org/a/maQSObIb495G79vXBZKErGNHQ)

Please check your environment tools and versions, _I recommend to use nodenv and set this node and yarn version local for the project_

Environment
**Node:** 12.16.2
**Yarn:** 1.22.4

### Note
For pull request reviews dont use "single comments", please use instead "Start a review"

**Review by acampos9 — APPROVED** [review]
image
all ok!!

**Comment by Oscarz90** [comment]
> image
> all ok!!

so I'll merge it to master!

**Pull request merged**
